spring:
  datasource:
    url: jdbc:mysql://47.75.90.35:3306/wms-activity?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: ezeeship1108
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 2
security:
  oauth2:
    client:
      clientId: ${spring.application.name}
      clientSecret: 123456
      accessTokenUri: http://47.75.209.221:5500/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      jwt:
        key-value: 123456
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:1111/eureka/
        fetch-registry: true