spring:
  datasource:
    url: jdbc:mysql://172.31.136.114:3306/wms-activity?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: ezeeship1108
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 5
security:
  oauth2:
    client:
      clientId: ${spring.application.name}
      clientSecret: 123456
      accessTokenUri: http://47.52.106.40:8011/api/auth-server/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      jwt:
        key-value: 123456
eureka:
    instance:
        preferIpAddress: true
    client:
        serviceUrl:
            defaultZone: http://172.31.136.111:1111/eureka/
        fetch-registry: true