spring:
  datasource:
    url: jdbc:mysql://rm-2evs6k3612k4fxv68.mysql.rds.aliyuncs.com:3306/wms-activity?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: Ezeeship1108
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 20
security:
  oauth2:
    client:
      clientId: ${spring.application.name}
      clientSecret: 123456
      accessTokenUri: http://192.168.0.75:5500/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      jwt:
        key-value: 123456
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://192.168.0.75:1111/eureka/
    fetch-registry: true
