spring:
    profiles:
        active: dev
    application:
        name: ezeeship-message-center
    http:
        converters:
            preferred-json-mapper: gson
    gson:
      date-format: yyyy-MM-dd HH:mm:ss
      serialize-nulls: true
      long-serialization-policy: string
    cloud:
        loadbalancer:
            retry:
                enabled: true
server:
    port: 5655
#mybatis
mybatis-plus:
  mapper-locations: classpath:/com/base/mapper/xml/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.base.entity
  #typeEnumsPackage: com.baomidou.springboot.entity.enums
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    fieldStrategy: 2
    #驼峰下划线转换
    dbColumnUnderline: false
    #mapUnderscoreToCamelCase: false
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: false
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: false
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: false
management.endpoints.web.exposure.include: shutdown,health,info
management.endpoint.shutdown.enabled: true
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000 #超时时间
ribbon: #ribbon容错策略
    ConnectTimeout: 10000
    ReadTimeout: 50000
    OkToRetryOnAllOperations: true
    MaxAutoRetriesNextServer: 0
    MaxAutoRetries: 0
logging:
    level:
        root: INFO
    config: classpath:log4j2-spring.xml