spring:
  datasource:
    url: jdbc:mysql://47.75.90.35:3306/ezeeship-message-center?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: ezeeship1108
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
          host: docker
          port: 5672
          username: yule
          password: ezeeship001
          publisher-confirms: true
          publisher-returns: true
          template:
              mandatory: true
          listener:
              simple:
                  concurrency: 2  #最小消息监听线程数
                  max-concurrency: 2 #最大消息监听线程数
  redis:
            database: 0
    # server host1
            host: docker
    # server password
    #        password:
    #connection port
            port: 6379
    # pool settings ...
            lettuce:
              pool:
                min-idle: 0
                max-active: 20
                max-idle: 20
  mail:
      properties:
        mail.smtp.connectiontimeout: 5000
        mail.smtp.timeout: 3000
        mail.smtp.writetimeout: 5000
        mail.smtp.auth: true
        mail.smtp.ssl.enable: true
        # mail.smtp.port: 465
      host: smtp.gmail.com
      username: support@ezeeship.com
      password: ezlp$2000
      port: 465
eureka:
    instance:
        preferIpAddress: true
        instance-id: ${eureka.instance.preferIpAddress}:${spring.application.name}:${server.port}
    client:
        serviceUrl:
            defaultZone: http://docker:1111/eureka/
        registryFetchIntervalSeconds: 5
loginUrl: https://rovaa.com/api/authcError