spring:
  datasource:
    url: jdbc:mysql://rm-2ev90wf4khdhh89p9.mysql.rds.aliyuncs.com:3306/wms-user?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: Ezeeship1108
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 30
security:
  oauth2:
    client:
      clientId: ${spring.application.name}
      clientSecret: 123456
      accessTokenUri: http://192.168.0.75:5500/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      jwt:
        key-value: 123456
warehouseUrl: https://shipout.us
omsUrl: http://shipout.co
paypal:
  mode: live
  successUrl: /#/app/setting/myWarehouse/success
  failUrl: /#/app/setting/myWarehouse/fail
  returnUrl: /api/wms-user/payment/paypal/process
  cancelUrl: /api/wms-user/payment/paypal/cancel
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://docker:1111/eureka/
    fetch-registry: true
