spring:
  datasource:
    url: jdbc:mysql://47.75.90.35:3306/wms-user?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: ezeeship1108
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 5
security:
  oauth2:
    client:
      clientId: ${spring.application.name}
      clientSecret: 123456
      accessTokenUri: http://47.75.209.221:5500/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      jwt:
        key-value: 123456
warehouseUrl: http://47.52.106.40:8011
omsUrl: http://47.52.106.40:8012
paypal:
    mode: sandbox
    successUrl: /#/app/setting/myWarehouse/success
    failUrl: /#/app/setting/myWarehouse/fail
    returnUrl: /api/wms-user/payment/paypal/process
    cancelUrl: /api/wms-user/payment/paypal/cancel
eureka:
  client:
    enabled: false

